kind: pipeline
type: docker
name: deploy-stage

trigger:
  branch:
    - feature/test
  event:
    - push

steps:
  - name: run-tests
    image: python:3.14-alpine
    environment:
      TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache git
      - rm -rf repo
      - git clone https://$TOKEN@github.com/K3rnys/warehouse_app.git repo
      - cd repo
      - git checkout feature/test
      - pip install -r requirements.txt
      - mypy app.py #анализатор ORM 
#      - bandit -r . -lll #статический анализатор уязвимостей 
      - flake8 . || true #Статический анализатор качества кода
      - pytest . # юнит тесты
      
  - name: alembic-migration-check
    image: python:3.14-alpine
    environment:
      DATABASE_URL: "sqlite:///data/warehouse.db"
    commands:
      - mkdir -p data                 # создаём директорию
      - chmod 777 data 
      - mkdir -p backups
      - TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
      - pip install -r requirements.txt
      - |
        if [ -f data/warehouse.db ]; then
          alembic stamp head
        fi
      # применяем все миграции
      - alembic upgrade head

      # пробуем автогенерацию
      - alembic revision --autogenerate -m "ci check"
      - cp data/warehouse.db backups/warehouse_$TIMESTAMP.db
      - echo "Database backup created successfully"

      # проверяем, что автогенерация не создаёт новых изменений
      #- alembic revision --autogenerate -m "ci check" --autogenerate-only-check
        
  - name: merge-to-dev
    image: alpine:3.20
    environment:
      TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache git
      - rm -rf repo
      - git clone https://$TOKEN@github.com/K3rnys/warehouse_app.git repo
      - cd repo
      - git checkout dev
      - git merge origin/feature/test --no-ff -m "Auto-merge feature/test into dev"
      - git push https://$TOKEN@github.com/K3rnys/warehouse_app.git dev

  - name: deploy-to-stage
    image: alpine:3.20
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: stage_dir
        path: /home/kernys/warehouse_app_stage
    commands:
      - apk add --no-cache git docker-cli docker-cli-compose
      - cd /home/kernys/warehouse_app_stage
      - git pull origin dev
      - docker compose down || true
      - docker compose up -d --build --force-recreate

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: stage_dir
    host:
      path: /home/kernys/warehouse_app_stage
